syntax = "proto3";

service AgentService {
  rpc RunTest(stream MasterCommand) returns (stream AgentResponse);
}

message MasterCommand {
  oneof command {
    StartTestCommand start      = 1;
    ChangeParamsCommand change  = 2;
    StopTestCommand stop        = 3;
  }
}

message StartTestCommand {
  string test_id    = 1;
  TestConfig config = 2;
}

message ChangeParamsCommand {
  string test_id            = 1;
  uint32 requests_per_sec   = 2;
}

message StopTestCommand {
  string test_id    = 1;
  StopReason reason = 2;
}

enum StopReason {
  USER        = 0;
  DURATION    = 1;
  ERROR       = 2;
}

message TestConfig {
  uint32 requests_per_sec   = 1;
  uint32 duration_sec       = 2;
  string url                = 3;
  LoadType load_type        = 4;
}

enum LoadType {
  SPIKE     = 0;
  CONSTANT  = 1;
  GRADUAL   = 2;
}

message AgentResponse {
  oneof response {
    TestStats   stats   = 1;
    AgentStatus status  = 2;
  }
}

message TestStats {
  string test_id    = 1;
  uint64 timestamp  = 2;

  uint32 requests_per_sec = 3;
  uint32 errors_per_sec   = 4;
  uint32 latency_ms       = 5;
  uint32 p50_ms           = 6;
  uint32 p95_ms           = 7;
  uint32 p99_ms           = 8;
}

enum AgentStatus {
  STARTING         = 0;
  RUNNING          = 1;
  PARAMS_APPLIED   = 2;
  STOPPING         = 3;
  FINISHED         = 4;
  ERROR            = 5;
}
